### ISSUE TITLE
Improve Electrode Native integration with CodePush

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#342]
Multiple improvements related to CodePush, targeting `v0.11.0` release.

- [X] Refactor CodePush integration to use CodePush management SDK programmatically in lieu of invoking CodePush command line CLI. 
**Done in :** https://github.com/electrode-io/electrode-native/pull/331

- [X] Add spinners to `ern code-push` command
**Issue :** https://github.com/electrode-io/electrode-native/issues/299
**Done in :** https://github.com/electrode-io/electrode-native/pull/347

- [X] Store more CodePush related information in Cauldron
**Issue :** https://github.com/electrode-io/electrode-native/issues/302
**Done in :** https://github.com/electrode-io/electrode-native/pull/337

- [X] `ern code-push` command should support semver for target version(s) 
**Issue :** https://github.com/electrode-io/electrode-native/issues/303
**Done in :** https://github.com/electrode-io/electrode-native/pull/369

- [X] Add an option in Cauldron to keep only X latest deployment info
**Issue :** https://github.com/electrode-io/electrode-native/issues/338
**Done in  :** https://github.com/electrode-io/electrode-native/pull/359

- [X] CodePush subcommands
**Issue :** https://github.com/electrode-io/electrode-native/issues/339
**Done in  :** https://github.com/electrode-io/electrode-native/pull/346

- [X] Add integration for `code-push patch` command
**Issue :** https://github.com/electrode-io/electrode-native/issues/340
**Done in  :** https://github.com/electrode-io/electrode-native/pull/364

- [X] Add integration for `code-push promote` command
**Issue :** https://github.com/electrode-io/electrode-native/issues/341
**Done in  :** https://github.com/electrode-io/electrode-native/pull/364

- [x] Once all tasks completed, updated Electrode Native documentation to reflect all changes
**Done in  :**

**Comment by belemaire** [comment]
Closing this EPIC as all tasks are now complete.
Few tweaks here and there to the code and the documentation will be made, but its now falling under regular maintenance.

**Comment by krunalsshah** [comment]
Well done
