### ISSUE TITLE
Cauldron improvements

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#396]
- [x] Simple linking of Cauldron schema with Electrode Native version https://github.com/electrode-io/electrode-native/issues/392
Done in :

- [x] Keep min Electrode Native version required in cauldron-api https://github.com/electrode-io/electrode-native/issues/393
Done in :

- [x] Add `cauldron upgrade` command https://github.com/electrode-io/electrode-native/issues/394
Done in :

- [x] Improve Cauldron schema https://github.com/electrode-io/electrode-native/issues/395
Done in :

- [x] Distinguish between MiniApp / JS API impl https://github.com/electrode-io/electrode-native/issues/306
Done in :
